/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as TechspecWriterImport } from './app/techspec-writer'
import { Route as TechSpecImport } from './app/tech-spec'
import { Route as PdfmanagerImport } from './app/pdf_manager'
import { Route as GamedevLogImport } from './app/gamedev-log'
import { Route as IndexImport } from './app/index'

// Create/Update Routes

const TechspecWriterRoute = TechspecWriterImport.update({
  id: '/techspec-writer',
  path: '/techspec-writer',
  getParentRoute: () => rootRoute,
} as any)

const TechSpecRoute = TechSpecImport.update({
  id: '/tech-spec',
  path: '/tech-spec',
  getParentRoute: () => rootRoute,
} as any)

const PdfmanagerRoute = PdfmanagerImport.update({
  id: '/pdf_manager',
  path: '/pdf_manager',
  getParentRoute: () => rootRoute,
} as any)

const GamedevLogRoute = GamedevLogImport.update({
  id: '/gamedev-log',
  path: '/gamedev-log',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/gamedev-log': {
      id: '/gamedev-log'
      path: '/gamedev-log'
      fullPath: '/gamedev-log'
      preLoaderRoute: typeof GamedevLogImport
      parentRoute: typeof rootRoute
    }
    '/pdf_manager': {
      id: '/pdf_manager'
      path: '/pdf_manager'
      fullPath: '/pdf_manager'
      preLoaderRoute: typeof PdfmanagerImport
      parentRoute: typeof rootRoute
    }
    '/tech-spec': {
      id: '/tech-spec'
      path: '/tech-spec'
      fullPath: '/tech-spec'
      preLoaderRoute: typeof TechSpecImport
      parentRoute: typeof rootRoute
    }
    '/techspec-writer': {
      id: '/techspec-writer'
      path: '/techspec-writer'
      fullPath: '/techspec-writer'
      preLoaderRoute: typeof TechspecWriterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gamedev-log': typeof GamedevLogRoute
  '/pdf_manager': typeof PdfmanagerRoute
  '/tech-spec': typeof TechSpecRoute
  '/techspec-writer': typeof TechspecWriterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gamedev-log': typeof GamedevLogRoute
  '/pdf_manager': typeof PdfmanagerRoute
  '/tech-spec': typeof TechSpecRoute
  '/techspec-writer': typeof TechspecWriterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/gamedev-log': typeof GamedevLogRoute
  '/pdf_manager': typeof PdfmanagerRoute
  '/tech-spec': typeof TechSpecRoute
  '/techspec-writer': typeof TechspecWriterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gamedev-log'
    | '/pdf_manager'
    | '/tech-spec'
    | '/techspec-writer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gamedev-log' | '/pdf_manager' | '/tech-spec' | '/techspec-writer'
  id:
    | '__root__'
    | '/'
    | '/gamedev-log'
    | '/pdf_manager'
    | '/tech-spec'
    | '/techspec-writer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamedevLogRoute: typeof GamedevLogRoute
  PdfmanagerRoute: typeof PdfmanagerRoute
  TechSpecRoute: typeof TechSpecRoute
  TechspecWriterRoute: typeof TechspecWriterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamedevLogRoute: GamedevLogRoute,
  PdfmanagerRoute: PdfmanagerRoute,
  TechSpecRoute: TechSpecRoute,
  TechspecWriterRoute: TechspecWriterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/gamedev-log",
        "/pdf_manager",
        "/tech-spec",
        "/techspec-writer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/gamedev-log": {
      "filePath": "gamedev-log.tsx"
    },
    "/pdf_manager": {
      "filePath": "pdf_manager.tsx"
    },
    "/tech-spec": {
      "filePath": "tech-spec.tsx"
    },
    "/techspec-writer": {
      "filePath": "techspec-writer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
