/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as TechSpecImport } from './app/tech-spec'
import { Route as PdfmanagerImport } from './app/pdf_manager'
import { Route as IndexImport } from './app/index'

// Create/Update Routes

const TechSpecRoute = TechSpecImport.update({
  id: '/tech-spec',
  path: '/tech-spec',
  getParentRoute: () => rootRoute,
} as any)

const PdfmanagerRoute = PdfmanagerImport.update({
  id: '/pdf_manager',
  path: '/pdf_manager',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pdf_manager': {
      id: '/pdf_manager'
      path: '/pdf_manager'
      fullPath: '/pdf_manager'
      preLoaderRoute: typeof PdfmanagerImport
      parentRoute: typeof rootRoute
    }
    '/tech-spec': {
      id: '/tech-spec'
      path: '/tech-spec'
      fullPath: '/tech-spec'
      preLoaderRoute: typeof TechSpecImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pdf_manager': typeof PdfmanagerRoute
  '/tech-spec': typeof TechSpecRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pdf_manager': typeof PdfmanagerRoute
  '/tech-spec': typeof TechSpecRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pdf_manager': typeof PdfmanagerRoute
  '/tech-spec': typeof TechSpecRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pdf_manager' | '/tech-spec'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pdf_manager' | '/tech-spec'
  id: '__root__' | '/' | '/pdf_manager' | '/tech-spec'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PdfmanagerRoute: typeof PdfmanagerRoute
  TechSpecRoute: typeof TechSpecRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PdfmanagerRoute: PdfmanagerRoute,
  TechSpecRoute: TechSpecRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pdf_manager",
        "/tech-spec"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pdf_manager": {
      "filePath": "pdf_manager.tsx"
    },
    "/tech-spec": {
      "filePath": "tech-spec.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
